name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/Notus.sln
    - name: Build
      run: dotnet build --no-restore src/Notus.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal  src/Notus.sln
