name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Get
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} src/Notus.sln
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build src/Notus.sln
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output . src/Notus.sln
    - name: Push
      run: dotnet nuget push notus.${VERSION}.nupkg --source https://nuget.pkg.github.com/alex-forbes/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
